//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeSisters.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredients()
        {
            this.NutritionalValues = new HashSet<NutritionalValues>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int IngredientId { get; set; }
        public string IngredientName { get; set; }
        public int CategoryId { get; set; }
        public int StorageLocationId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual IngredientCategories IngredientCategories { get; set; }
        public virtual StorageLocations StorageLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutritionalValues> NutritionalValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
