//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeSisters.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRecipes
    {
        public int MenuRecipeId { get; set; }
        public int MenuId { get; set; }
        public int RecipeId { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
