//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeSisters.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutritionalValues
    {
        public int NutritionalValueId { get; set; }
        public int IngredientId { get; set; }
        public Nullable<decimal> Proteins { get; set; }
        public Nullable<decimal> Fats { get; set; }
        public Nullable<decimal> Carbohydrates { get; set; }
        public Nullable<decimal> EnergyValue { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
    }
}
